### ISSUE TITLE
Problem with project names with dashes

### ISSUE THREAD

**Issue by gimenete** [clevertech/boilerplate#7]
docker-compose has problems with project names with dashes.
https://github.com/docker/compose/issues/869

One way to fix this is to just remove the dashes when the project name is replaced here: https://github.com/clevertech/boilerplate/blob/master/docker/run#L5

There's a script that clones the project and replaces the name of the project in multiple files: https://github.com/clevertech/boilerplate/tree/create-boilerplate-app

for `docker/run` it should remove the dashes

**Comment by nstraub** [comment]
Could we change dashes to snake_case? (to keep the names clear)

**Comment by gimenete** [comment]
Sure 👍  if that works

**Comment by nstraub** [comment]
I ended up fixing it without having to sacrifice dashes... so it's still consistent. I'll push as soon as I have write permissions.
I did change some dashes with underscores though... the ones pertaining to db users and names. Since databases don't like hyphens in their names I figured it'd be best to use undersores

**Comment by chadfurman** [comment]
we should close this
